/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CustomQueryIndexImport } from './routes/custom-query/index'
import { Route as ContainerIndexImport } from './routes/container/index'
import { Route as CustomQueryEditorImport } from './routes/custom-query/editor'
import { Route as CustomQueryCustomQueryNameImport } from './routes/custom-query/$customQueryName'
import { Route as ContainerEditorImport } from './routes/container/editor'
import { Route as ContainerContainerNameIndexImport } from './routes/container/$containerName/index'
import { Route as ContainerContainerNameSearchImport } from './routes/container/$containerName/search'
import { Route as ContainerContainerNameAnnotationEditorImport } from './routes/container/$containerName/annotation/editor'
import { Route as ContainerContainerNameAnnotationAnnotationNameImport } from './routes/container/$containerName/annotation/$annotationName'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CustomQueryIndexRoute = CustomQueryIndexImport.update({
  id: '/custom-query/',
  path: '/custom-query/',
  getParentRoute: () => rootRoute,
} as any)

const ContainerIndexRoute = ContainerIndexImport.update({
  id: '/container/',
  path: '/container/',
  getParentRoute: () => rootRoute,
} as any)

const CustomQueryEditorRoute = CustomQueryEditorImport.update({
  id: '/custom-query/editor',
  path: '/custom-query/editor',
  getParentRoute: () => rootRoute,
} as any)

const CustomQueryCustomQueryNameRoute = CustomQueryCustomQueryNameImport.update(
  {
    id: '/custom-query/$customQueryName',
    path: '/custom-query/$customQueryName',
    getParentRoute: () => rootRoute,
  } as any,
)

const ContainerEditorRoute = ContainerEditorImport.update({
  id: '/container/editor',
  path: '/container/editor',
  getParentRoute: () => rootRoute,
} as any)

const ContainerContainerNameIndexRoute =
  ContainerContainerNameIndexImport.update({
    id: '/container/$containerName/',
    path: '/container/$containerName/',
    getParentRoute: () => rootRoute,
  } as any)

const ContainerContainerNameSearchRoute =
  ContainerContainerNameSearchImport.update({
    id: '/container/$containerName/search',
    path: '/container/$containerName/search',
    getParentRoute: () => rootRoute,
  } as any)

const ContainerContainerNameAnnotationEditorRoute =
  ContainerContainerNameAnnotationEditorImport.update({
    id: '/container/$containerName/annotation/editor',
    path: '/container/$containerName/annotation/editor',
    getParentRoute: () => rootRoute,
  } as any)

const ContainerContainerNameAnnotationAnnotationNameRoute =
  ContainerContainerNameAnnotationAnnotationNameImport.update({
    id: '/container/$containerName/annotation/$annotationName',
    path: '/container/$containerName/annotation/$annotationName',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/container/editor': {
      id: '/container/editor'
      path: '/container/editor'
      fullPath: '/container/editor'
      preLoaderRoute: typeof ContainerEditorImport
      parentRoute: typeof rootRoute
    }
    '/custom-query/$customQueryName': {
      id: '/custom-query/$customQueryName'
      path: '/custom-query/$customQueryName'
      fullPath: '/custom-query/$customQueryName'
      preLoaderRoute: typeof CustomQueryCustomQueryNameImport
      parentRoute: typeof rootRoute
    }
    '/custom-query/editor': {
      id: '/custom-query/editor'
      path: '/custom-query/editor'
      fullPath: '/custom-query/editor'
      preLoaderRoute: typeof CustomQueryEditorImport
      parentRoute: typeof rootRoute
    }
    '/container/': {
      id: '/container/'
      path: '/container'
      fullPath: '/container'
      preLoaderRoute: typeof ContainerIndexImport
      parentRoute: typeof rootRoute
    }
    '/custom-query/': {
      id: '/custom-query/'
      path: '/custom-query'
      fullPath: '/custom-query'
      preLoaderRoute: typeof CustomQueryIndexImport
      parentRoute: typeof rootRoute
    }
    '/container/$containerName/search': {
      id: '/container/$containerName/search'
      path: '/container/$containerName/search'
      fullPath: '/container/$containerName/search'
      preLoaderRoute: typeof ContainerContainerNameSearchImport
      parentRoute: typeof rootRoute
    }
    '/container/$containerName/': {
      id: '/container/$containerName/'
      path: '/container/$containerName'
      fullPath: '/container/$containerName'
      preLoaderRoute: typeof ContainerContainerNameIndexImport
      parentRoute: typeof rootRoute
    }
    '/container/$containerName/annotation/$annotationName': {
      id: '/container/$containerName/annotation/$annotationName'
      path: '/container/$containerName/annotation/$annotationName'
      fullPath: '/container/$containerName/annotation/$annotationName'
      preLoaderRoute: typeof ContainerContainerNameAnnotationAnnotationNameImport
      parentRoute: typeof rootRoute
    }
    '/container/$containerName/annotation/editor': {
      id: '/container/$containerName/annotation/editor'
      path: '/container/$containerName/annotation/editor'
      fullPath: '/container/$containerName/annotation/editor'
      preLoaderRoute: typeof ContainerContainerNameAnnotationEditorImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/container/editor': typeof ContainerEditorRoute
  '/custom-query/$customQueryName': typeof CustomQueryCustomQueryNameRoute
  '/custom-query/editor': typeof CustomQueryEditorRoute
  '/container': typeof ContainerIndexRoute
  '/custom-query': typeof CustomQueryIndexRoute
  '/container/$containerName/search': typeof ContainerContainerNameSearchRoute
  '/container/$containerName': typeof ContainerContainerNameIndexRoute
  '/container/$containerName/annotation/$annotationName': typeof ContainerContainerNameAnnotationAnnotationNameRoute
  '/container/$containerName/annotation/editor': typeof ContainerContainerNameAnnotationEditorRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/container/editor': typeof ContainerEditorRoute
  '/custom-query/$customQueryName': typeof CustomQueryCustomQueryNameRoute
  '/custom-query/editor': typeof CustomQueryEditorRoute
  '/container': typeof ContainerIndexRoute
  '/custom-query': typeof CustomQueryIndexRoute
  '/container/$containerName/search': typeof ContainerContainerNameSearchRoute
  '/container/$containerName': typeof ContainerContainerNameIndexRoute
  '/container/$containerName/annotation/$annotationName': typeof ContainerContainerNameAnnotationAnnotationNameRoute
  '/container/$containerName/annotation/editor': typeof ContainerContainerNameAnnotationEditorRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/container/editor': typeof ContainerEditorRoute
  '/custom-query/$customQueryName': typeof CustomQueryCustomQueryNameRoute
  '/custom-query/editor': typeof CustomQueryEditorRoute
  '/container/': typeof ContainerIndexRoute
  '/custom-query/': typeof CustomQueryIndexRoute
  '/container/$containerName/search': typeof ContainerContainerNameSearchRoute
  '/container/$containerName/': typeof ContainerContainerNameIndexRoute
  '/container/$containerName/annotation/$annotationName': typeof ContainerContainerNameAnnotationAnnotationNameRoute
  '/container/$containerName/annotation/editor': typeof ContainerContainerNameAnnotationEditorRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/container/editor'
    | '/custom-query/$customQueryName'
    | '/custom-query/editor'
    | '/container'
    | '/custom-query'
    | '/container/$containerName/search'
    | '/container/$containerName'
    | '/container/$containerName/annotation/$annotationName'
    | '/container/$containerName/annotation/editor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/container/editor'
    | '/custom-query/$customQueryName'
    | '/custom-query/editor'
    | '/container'
    | '/custom-query'
    | '/container/$containerName/search'
    | '/container/$containerName'
    | '/container/$containerName/annotation/$annotationName'
    | '/container/$containerName/annotation/editor'
  id:
    | '__root__'
    | '/'
    | '/container/editor'
    | '/custom-query/$customQueryName'
    | '/custom-query/editor'
    | '/container/'
    | '/custom-query/'
    | '/container/$containerName/search'
    | '/container/$containerName/'
    | '/container/$containerName/annotation/$annotationName'
    | '/container/$containerName/annotation/editor'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContainerEditorRoute: typeof ContainerEditorRoute
  CustomQueryCustomQueryNameRoute: typeof CustomQueryCustomQueryNameRoute
  CustomQueryEditorRoute: typeof CustomQueryEditorRoute
  ContainerIndexRoute: typeof ContainerIndexRoute
  CustomQueryIndexRoute: typeof CustomQueryIndexRoute
  ContainerContainerNameSearchRoute: typeof ContainerContainerNameSearchRoute
  ContainerContainerNameIndexRoute: typeof ContainerContainerNameIndexRoute
  ContainerContainerNameAnnotationAnnotationNameRoute: typeof ContainerContainerNameAnnotationAnnotationNameRoute
  ContainerContainerNameAnnotationEditorRoute: typeof ContainerContainerNameAnnotationEditorRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContainerEditorRoute: ContainerEditorRoute,
  CustomQueryCustomQueryNameRoute: CustomQueryCustomQueryNameRoute,
  CustomQueryEditorRoute: CustomQueryEditorRoute,
  ContainerIndexRoute: ContainerIndexRoute,
  CustomQueryIndexRoute: CustomQueryIndexRoute,
  ContainerContainerNameSearchRoute: ContainerContainerNameSearchRoute,
  ContainerContainerNameIndexRoute: ContainerContainerNameIndexRoute,
  ContainerContainerNameAnnotationAnnotationNameRoute:
    ContainerContainerNameAnnotationAnnotationNameRoute,
  ContainerContainerNameAnnotationEditorRoute:
    ContainerContainerNameAnnotationEditorRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/container/editor",
        "/custom-query/$customQueryName",
        "/custom-query/editor",
        "/container/",
        "/custom-query/",
        "/container/$containerName/search",
        "/container/$containerName/",
        "/container/$containerName/annotation/$annotationName",
        "/container/$containerName/annotation/editor"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/container/editor": {
      "filePath": "container/editor.tsx"
    },
    "/custom-query/$customQueryName": {
      "filePath": "custom-query/$customQueryName.tsx"
    },
    "/custom-query/editor": {
      "filePath": "custom-query/editor.tsx"
    },
    "/container/": {
      "filePath": "container/index.tsx"
    },
    "/custom-query/": {
      "filePath": "custom-query/index.tsx"
    },
    "/container/$containerName/search": {
      "filePath": "container/$containerName/search.tsx"
    },
    "/container/$containerName/": {
      "filePath": "container/$containerName/index.tsx"
    },
    "/container/$containerName/annotation/$annotationName": {
      "filePath": "container/$containerName/annotation/$annotationName.tsx"
    },
    "/container/$containerName/annotation/editor": {
      "filePath": "container/$containerName/annotation/editor.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
