/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ContainerIndexImport } from './routes/container/index'
import { Route as ContainerContainerIdImport } from './routes/container/$containerId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ContainerIndexRoute = ContainerIndexImport.update({
  id: '/container/',
  path: '/container/',
  getParentRoute: () => rootRoute,
} as any)

const ContainerContainerIdRoute = ContainerContainerIdImport.update({
  id: '/container/$containerId',
  path: '/container/$containerId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/container/$containerId': {
      id: '/container/$containerId'
      path: '/container/$containerId'
      fullPath: '/container/$containerId'
      preLoaderRoute: typeof ContainerContainerIdImport
      parentRoute: typeof rootRoute
    }
    '/container/': {
      id: '/container/'
      path: '/container'
      fullPath: '/container'
      preLoaderRoute: typeof ContainerIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/container/$containerId': typeof ContainerContainerIdRoute
  '/container': typeof ContainerIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/container/$containerId': typeof ContainerContainerIdRoute
  '/container': typeof ContainerIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/container/$containerId': typeof ContainerContainerIdRoute
  '/container/': typeof ContainerIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/container/$containerId' | '/container'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/container/$containerId' | '/container'
  id: '__root__' | '/' | '/container/$containerId' | '/container/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContainerContainerIdRoute: typeof ContainerContainerIdRoute
  ContainerIndexRoute: typeof ContainerIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContainerContainerIdRoute: ContainerContainerIdRoute,
  ContainerIndexRoute: ContainerIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/container/$containerId",
        "/container/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/container/$containerId": {
      "filePath": "container/$containerId.tsx"
    },
    "/container/": {
      "filePath": "container/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
