/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ContainerIndexImport } from './routes/container/index'
import { Route as ContainerContainerNameIndexImport } from './routes/container/$containerName/index'
import { Route as ContainerContainerNameAnnotationFormImport } from './routes/container/$containerName/annotation/form'
import { Route as ContainerContainerNameAnnotationAnnotationNameImport } from './routes/container/$containerName/annotation/$annotationName'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ContainerIndexRoute = ContainerIndexImport.update({
  id: '/container/',
  path: '/container/',
  getParentRoute: () => rootRoute,
} as any)

const ContainerContainerNameIndexRoute =
  ContainerContainerNameIndexImport.update({
    id: '/container/$containerName/',
    path: '/container/$containerName/',
    getParentRoute: () => rootRoute,
  } as any)

const ContainerContainerNameAnnotationFormRoute =
  ContainerContainerNameAnnotationFormImport.update({
    id: '/container/$containerName/annotation/form',
    path: '/container/$containerName/annotation/form',
    getParentRoute: () => rootRoute,
  } as any)

const ContainerContainerNameAnnotationAnnotationNameRoute =
  ContainerContainerNameAnnotationAnnotationNameImport.update({
    id: '/container/$containerName/annotation/$annotationName',
    path: '/container/$containerName/annotation/$annotationName',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/container/': {
      id: '/container/'
      path: '/container'
      fullPath: '/container'
      preLoaderRoute: typeof ContainerIndexImport
      parentRoute: typeof rootRoute
    }
    '/container/$containerName/': {
      id: '/container/$containerName/'
      path: '/container/$containerName'
      fullPath: '/container/$containerName'
      preLoaderRoute: typeof ContainerContainerNameIndexImport
      parentRoute: typeof rootRoute
    }
    '/container/$containerName/annotation/$annotationName': {
      id: '/container/$containerName/annotation/$annotationName'
      path: '/container/$containerName/annotation/$annotationName'
      fullPath: '/container/$containerName/annotation/$annotationName'
      preLoaderRoute: typeof ContainerContainerNameAnnotationAnnotationNameImport
      parentRoute: typeof rootRoute
    }
    '/container/$containerName/annotation/form': {
      id: '/container/$containerName/annotation/form'
      path: '/container/$containerName/annotation/form'
      fullPath: '/container/$containerName/annotation/form'
      preLoaderRoute: typeof ContainerContainerNameAnnotationFormImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/container': typeof ContainerIndexRoute
  '/container/$containerName': typeof ContainerContainerNameIndexRoute
  '/container/$containerName/annotation/$annotationName': typeof ContainerContainerNameAnnotationAnnotationNameRoute
  '/container/$containerName/annotation/form': typeof ContainerContainerNameAnnotationFormRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/container': typeof ContainerIndexRoute
  '/container/$containerName': typeof ContainerContainerNameIndexRoute
  '/container/$containerName/annotation/$annotationName': typeof ContainerContainerNameAnnotationAnnotationNameRoute
  '/container/$containerName/annotation/form': typeof ContainerContainerNameAnnotationFormRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/container/': typeof ContainerIndexRoute
  '/container/$containerName/': typeof ContainerContainerNameIndexRoute
  '/container/$containerName/annotation/$annotationName': typeof ContainerContainerNameAnnotationAnnotationNameRoute
  '/container/$containerName/annotation/form': typeof ContainerContainerNameAnnotationFormRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/container'
    | '/container/$containerName'
    | '/container/$containerName/annotation/$annotationName'
    | '/container/$containerName/annotation/form'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/container'
    | '/container/$containerName'
    | '/container/$containerName/annotation/$annotationName'
    | '/container/$containerName/annotation/form'
  id:
    | '__root__'
    | '/'
    | '/container/'
    | '/container/$containerName/'
    | '/container/$containerName/annotation/$annotationName'
    | '/container/$containerName/annotation/form'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContainerIndexRoute: typeof ContainerIndexRoute
  ContainerContainerNameIndexRoute: typeof ContainerContainerNameIndexRoute
  ContainerContainerNameAnnotationAnnotationNameRoute: typeof ContainerContainerNameAnnotationAnnotationNameRoute
  ContainerContainerNameAnnotationFormRoute: typeof ContainerContainerNameAnnotationFormRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContainerIndexRoute: ContainerIndexRoute,
  ContainerContainerNameIndexRoute: ContainerContainerNameIndexRoute,
  ContainerContainerNameAnnotationAnnotationNameRoute:
    ContainerContainerNameAnnotationAnnotationNameRoute,
  ContainerContainerNameAnnotationFormRoute:
    ContainerContainerNameAnnotationFormRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/container/",
        "/container/$containerName/",
        "/container/$containerName/annotation/$annotationName",
        "/container/$containerName/annotation/form"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/container/": {
      "filePath": "container/index.tsx"
    },
    "/container/$containerName/": {
      "filePath": "container/$containerName/index.tsx"
    },
    "/container/$containerName/annotation/$annotationName": {
      "filePath": "container/$containerName/annotation/$annotationName.tsx"
    },
    "/container/$containerName/annotation/form": {
      "filePath": "container/$containerName/annotation/form.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
